version: '3'

services:
  containerdb:
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: hyeondle
      MYSQL_PASSWORD: password
    networks:
      - mynetwork
    restart: on-failure

  containerwordpressphp:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - containerdb
    networks:
      - mynetwork
    restart: on-failure

  containernginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/wordpress
    depends_on:
      - containerwordpressphp
    ports:
      - "442:443"
    networks:
      - mynetwork
    restart: on-failure

networks:
  mynetwork:

volumes:
  db:
  wordpress:
